import Head from "next/head";
import Image from "next/image";
import Header from "../src/Component/Header";
import Loginpage from "../src/Pages/LogInPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link />
      </Head>

      <main className="">
        <Header></Header>
        <Loginpage />
      </main>

      <footer></footer>
    </div>
  );
}
